import { Overpass_Mono } from "next/font/google";
import "./globals.css";

const overpassMono = Overpass_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={overpassMono.className}>{children}</body>
    </html>
  );
}
